server:
  port: 9090
spring:
  application:
    name: "learn"
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:mem:learn"
    driver-class-name: "org.h2.Driver"
    hikari:
      maximum-pool-size: 25
  jpa:
    hibernate:
      ddl-auto: "create"
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: learn-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.hibernate.SQL: DEBUG

learn:
  kafka:
    server: localhost:9092
    topic: learn-topic
    group: group-id

